#!/usr/bin/env python3

import sys
from itertools import takewhile

import requests


def exists(bugno: int) -> bool:
    r = requests.get(f"https://bugzilla.proxmox.com/rest/bug/{bugno}", timeout=10)
    data = r.json()

    if data.get("error"): return data.get("code") == 102
    return bool(data.get("bugs"))


def get_url(msg: str) -> str | None:
    prefix = next((p for p in ["fix #", "partially-fix #"] if msg.startswith(p)), None)
    if not prefix: return None
    idx = len(prefix)

    bugno = "".join([x for x in takewhile(lambda x: x.isdigit(), msg[idx:])])
    if not bugno.isdigit() or not exists(int(bugno)): return None

    return f"https://bugzilla.proxmox.com/show_bug.cgi?id={bugno}"


def write(msg: str, msgfile: str, url: str):
    written = False
    seen = {}
    trailers = ["co-authored-by", "originally-by", "signed-off-by"]
    link_line = f"Link: {url}"

    with open(msgfile, "w") as f:
        for line in msg.splitlines():
            if seen.get(line) or line == link_line: continue

            ll = line.lower()
            if any(ll.startswith(x) for x in trailers):
                seen[line] = True

                if not written:
                    _ = f.write(f"{link_line}\n")
                    written = True

            _ = f.write(f"{line}\n")


def main():
    msgfile = sys.argv[1]

    with open(msgfile, "r") as f: msg = f.read()

    url = get_url(msg)
    if not url: sys.exit(0)

    print(f"found bug matching subject line at {url}, adding trailer")

    write(msg, msgfile, url)


if __name__ == "__main__":
    main()
